name: Brainbytes CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  
           cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Lint (optional)
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
