name: Brainbytes CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'  # Fixed path pattern

      - name: Install dependencies
        run: npm ci  # Changed from install to ci for consistency

      - name: Run Lint (optional)
        run: npm run lint || echo "Linting failed but continuing"

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build